services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:master
    container_name: couchdb-obsidian-livesync
    restart: always
    environment:
      SERVER_URL: http://ip.address:port or https://domain.name-if-already--using a reverse proxy
      COUCHDB_USER: username
      COUCHDB_PASSWORD: yourpassword
      COUCHDB_DATABASE: nameofyourdatabase
    ports:
      - "5984:5984"  # change the external port if rtunning multiple instances
    volumes:
      - ./data:/opt/couchdb/data